### ISSUE TITLE
Yaru Dark Doesn't seem to work.

### ISSUE THREAD

**Issue by TimApp1e** [flathub/org.gtk.Gtk3theme.Yaru#2]
For a couple days I didn't think Yaru worked at all, but it's because I had chosen the Dark version. Yaru works fine, but Yaru Dark doesn't seem to work. Don't know if this needs to be a separate package.

**Comment by TingPing** [comment]
It has to be a new package. If you can confirm the name of that theme I'll make it now `Yaru-dark` or `Yaru-Dark`, etc.

**Comment by TingPing** [comment]
Looks like `-dark`

**Comment by ahayzen** [comment]
@TingPing this is what I get in a VM when changing the theme with Tweaks.
```
$ gtk-query-settings |grep -i gtk-theme
                     gtk-theme-name: "Yaru"
$ gtk-query-settings |grep -i gtk-theme
                     gtk-theme-name: "Yaru-dark"
```

**Comment by TimApp1e** [comment]
I see the same

**Comment by TingPing** [comment]
Repo made, will push the package soon: https://github.com/flathub/org.gtk.Gtk3theme.Yaru-dark

**Comment by TimApp1e** [comment]
Thanks

**Comment by clobrano** [comment]
Yaru dark hasn't been released yet

**Comment by ahayzen** [comment]
@TingPing awesome thanks, it works now!

@clobrano It's in the Ubuntu 18.10 release candidate, so i assume will be officially released next week? But it's good to have in flathub as people testing the release candidate were thinking it was a bug in flatpak.

**Comment by TimApp1e** [comment]
Tested this..works like a charm now... thanks again.
