### ISSUE TITLE
Yaru dark is not used

### ISSUE THREAD

**Issue by clobrano** [flathub/org.gtk.Gtk3theme.Yaru#5]

**Comment by TingPing** [comment]
This isn't a complete sentence but its packaged here; https://github.com/flathub/org.gtk.Gtk3theme.Yaru-dark

**Comment by clobrano** [comment]
Hi @TingPing, yes I knew it, but I have no access there and there's nobody maintaining it. There's one PR pending since the 22nd of February (which is outdated now of course)

Moreover, I had a conversation some time ago (I need to find it) where someone told me that it wasn't necessary a different repo

**Comment by TingPing** [comment]
You were sent an invite to that repo when you were with this one, so just accept it =)
